import opendssdirect as dss

# Load the DSS script line by line. You can also redirect a full DSS file with dss.Text.Command("redirect yourfile.dss")

dss.Text.Command('redirect Run1/Master.dss')

# Save all monitor data files (csv generated by OpenDSS)
dss.Monitors.SaveAll()

# Get the monitors list
monitors = dss.Monitors.AllNames()

# Find the index of PotenciaBarra monitor
index = None
for i, name in enumerate(monitors):
    if name.lower() == "potenciabarra":
        index = i
        break

if index is not None:
    dss.Monitors.Name(monitors[index])
    # Get monitor data as a matrix (list of floats)
    data = dss.Monitors.Channel(1)  # channel 1 usually corresponds to active power in kW
    print("PotenciaBarra monitor active power data:", data)
else:
    print("PotenciaBarra monitor not found")
