import streamlit as st
from pathlib import Path

import opendssdirect as dss

SOLVER = "OpenDSS"

def solveFile(solver, path):
    # Load the DSS script line by line. You can also redirect a full DSS file with dss.Text.Command("redirect yourfile.dss")
    dss.Text.Command('redirect '+ path)

    # Save all monitor data files (csv generated by OpenDSS)
    dss.Monitors.SaveAll()

    # Get the monitors list
    monitors = dss.Monitors.AllNames()
    return monitors

def getMonitorDataByName(monitor_name, monitors):
    # Find the index of the specified monitor
    index = None
    for i, name in enumerate(monitors):
        if name.lower() == monitor_name.lower():
            index = i
            break

    if index is not None:
        dss.Monitors.Name(monitors[index])
        # Get monitor data as a matrix (list of floats)
        data = dss.Monitors.Channel(1)  # channel 1 usually corresponds to active power in kW
        return data
    else:
        return None
    
def run_solver_with_monitor(solver, path, monitor_name=None):
    monitors = solveFile(solver, path)
    if monitor_name is None:
        return monitors
    return getMonitorDataByName(monitor_name, monitors)

st.set_page_config(page_title="Carregando", page_icon="⏳")

DEFAULT_SESSION_STATE = {
    "pending_main_file": None,
    "pending_monitor_name": None,
    "pending_extract_dir": None,
}

for key, default in DEFAULT_SESSION_STATE.items():
    st.session_state.setdefault(key, default)

main_file = st.session_state["pending_main_file"]
monitor_name = st.session_state["pending_monitor_name"]
extract_dir = st.session_state["pending_extract_dir"]

if not all([main_file, monitor_name, extract_dir]):
    st.warning("Dados pendentes não encontrados. Volte para a página inicial.")
    st.stop()

st.write("Carregando...")
st.write(f"- Arquivo principal: {main_file}")
st.write(f"- Nome do monitor: {monitor_name}")
st.write(f"- Diretório extraído: {extract_dir}")

st.session_state["solver_result"] = run_solver_with_monitor("OPENDSS", extract_dir + "/" + main_file, monitor_name)
resultado = st.session_state["solver_result"]
if resultado is None:
    st.warning("Monitor não encontrado.")
else:
    st.dataframe({"valor": resultado})
st.success("Processamento concluído.")