import opendssdirect as dss

def solveFile(solver, path):
    # Load the DSS script line by line. You can also redirect a full DSS file with dss.Text.Command("redirect yourfile.dss")
    dss.Text.Command('redirect Run1/Master.dss')

    # Save all monitor data files (csv generated by OpenDSS)
    dss.Monitors.SaveAll()

    # Get the monitors list
    monitors = dss.Monitors.AllNames()
    return monitors

def getMonitorDataByName(monitor_name, monitors):
    # Find the index of the specified monitor
    index = None
    for i, name in enumerate(monitors):
        if name.lower() == monitor_name.lower():
            index = i
            break

    if index is not None:
        dss.Monitors.Name(monitors[index])
        # Get monitor data as a matrix (list of floats)
        data = dss.Monitors.Channel(1)  # channel 1 usually corresponds to active power in kW
        return data
    else:
        return None
    
if __name__ == "__main__":
    solver = "OpenDSS"
    path = "Run1/Master.dss"

    monitors = solveFile(solver, path)

    monitor_name = "potenciabarra"  # Replace with your actual monitor name
    data = getMonitorDataByName(monitor_name, monitors)

    if data is not None:
        print(f"Data for monitor '{monitor_name}':")
        print(data)
    else:
        print(f"Monitor '{monitor_name}' not found.")